[GameSettings]
;Harder Stealth, vanilla value commented after each setting, with explanation if I can be bothered
;fSneakUnseenMin = 0
;0, if the result of the detection calc is higher than this, a non-hostile or unaware observer will detect the target (values higher than zero have no effect?)
;fSneakNoticedMin = -20
;-20, if the result of the detection calc is higher than this, the observer is aware that the target is near and sneaking, but has not necessarily detected the target
;fSneakLostMin = -20
;-20, detection calc result has to fall below this value for the observer to stop looking for the target, only used after the target has been detected by a hostile observer
iAICombatMinDetection = -25
;-50, detect calc result has to fall below this value for the observer to lose track of the target, if they are in combat with each other
fSneakTargetAttackBonus = 125
;100, the bonus given to an observer that is attacked by the target
fSneakTargetInCombatBonus = 75
;25, penalty applied for any target that is in active combat, higher value = easier for observers not currently in combat with target to detect them
fSneakBaseValue = -10
;-25, base value for the combined detection calc, higher than -8ish gives some issues(?) with scripted encounters (jail prologue)
fSneakSkillMult = 0.75
;0.5, determines how much the Sneak skill matters in detection calculations
;observer Sneak skill is multiplied by DistanceFactor (a value between 0.0~ and 1.0 depending on the relative distance of target and observer)
;then subtracted by the targets Sneak skill before being multiplied by fSneakSkillMult to give the final SkillBonus value
fSneakMaxDistance = 3500
;1500, max distance (in units) a target can be detected at, default value of 1500 = 21-ish meters? value is multiplied by fSneakExteriorDistanceMult when in an exterior cell
;fSneakExteriorDistanceMult = 2.0
;1.5 in Remaster(?), 2.0 in Oldblivion
fSneakSleepBonus = -5
;-10, the "bonus" an observer gets to detect a sneaking target when the observer is sleeping, lower value = harder to wake up
fSneakSoundsMult = 3.5
;1.6, base multiplier for any sound based detection, value is multiplied by distance, movement and LoS values
fSneakBootWeightBase = 0.0
;14, base penalty for wearing any boots, we set this to 0.0 so that its the actual weight of the boots that matters
fSneakBootWeightMult = 4
;1, weight of boots is multiplied by this, then added together with the base penalty
;with WeightBase and WeightMult at 0.0 and 8, your "Sack Cloth Sandals" at 2.0 weight gives a value of 16
;same as the vanilla result, with heavier boots having a much larger impact than with the default values
fSneakRunningMult = 2.4
;1.3, the result of (...WeightBase + ...WeightMult*boot weight) is multiplied by this value if the target is running
fSneakSoundLosMult = 0.1
;1, final multiplier for sound based detection, if there is no LoS between the observer and the target
fDetectionSneakLightMod = 0
;15 in remaster?, -5 in Oldblivion
;this is added with the light level (0-100, dark-light) to determine how much relative light is on the target, this value is multiplied by 3 (default) if the observer has any Night Eye effects
fSneakLightMult = 2.8
;1.4, multiplier for any light-based detection, higher = easier for the observer to detect the target based on light
fSneakSwimmingLightMult = 0.25
;0.5, multiplier for light-based detection if the target is swimming
iSneakSkillUseDistance = 2300
;1000, the max range in units from any observer that Sneak experience will be granted while sneaking undetected
iNumberActorsInCombatPlayer = 30
;10, Controls the number of actors in "combat mode" with the player. If there are more agressive NPCs then this setting allows, they will "wait"; i.e. they will hang back