[Meshes]

; EditorID: aaRMMGNecroQuestMap | Name: Mages Guild Bounty Notice
;000ED3=/Game/Forms/items/book/BlankSheet.BlankSheet
;000ED3=/Game/Forms/items/book/Broadsheet01PoorTaxes.Broadsheet01PoorTaxes
000ED3=/Game/Forms/items/book/ClutterShoppingList03.ClutterShoppingList03

; EditorID: aaRMMGMagicStone03 | Name: Rendyl Stone
003100=/Game/Forms/worldobjects/static/ARWelkydClusterGreen01.ARWelkydClusterGreen01

; EditorID: aaRMMGAncientKnowledgeBook | Name: Ancient Manuscript
0067D8=/Game/Forms/items/book/ScrollStandardSummonClannfearExpert.ScrollStandardSummonClannfearExpert

; EditorID: aaRMMGConjurerBossMaleHighElf | Name: Notorious Conjurer
007CC5=/Game/Forms/actors/npc/ConjurerMaleHighElf4.ConjurerMaleHighElf4
