; This configuration file loads on game startup
; In-game keybinds are disabled by default, set EnableKeybinds=on below to enable them on game start - or it can be turned on in game
; Press F12 to load the current configuration file while in-game - you can now edit the configuration file and load the changes while in-game
; If a setting does not specify a keybind, then it can only be changed via the configuration file
; The 'game' option for settings below tells Ultra Plus to leave the setting at game default
; CTRL+F12 will reset the configuration file to default values - you may need to restart game for "game" controlled settings to load game values

; game/default/ultra/insane/more_insane/even_more_insane; extends view distances for lights, skeletal meshes, and static meshes
ExtendedViewDistance=default

; F4
; off/on; fixes the foliage and other outline artifacts against the sky but causes some above water flickering when player is underwater
FixFoliageAgainstSky=on

; F10
; game/off/on/on_with_lumen; allows disabling the color grading that applies a fantasy color map to the game, turn off if you want try a more realistic feel
Fog=on

; CTRL + F9
; lumen/ssao/gtao; ambient occlusion method - SSAO is vanilla, Lumen is U+ default
LightingAO=lumen

; F6
; lighting_mode_controlled/x64/x48/x32/x24/x16/x8; allow users the ability to downsample the lighting more than the mod allows by default, it will be applied after other lighting settings - this is one of the settings that impacts performance the most - by default U+ runs at x24 in standard mode
LightingDownsampleFactorOverride=x32

; F8
; standard; standard for default enhanced lighting - no other options available at this time
LightingMode=standard

; CTRL + F10
; game/low/standard/high/epic/insane/insane_highres/noframes; low for more FPS if you are really struggling with FPS, standard for default settings, high for higher VRAM usage and slight performance hit, epic for higher VRAM usage and performance hit, insane is maximum gather quality at standard resolution, insane_highres is maximum gather quality at higher resolution, noframes is the maximum possible lighting quality and probably only feasible for photos
LightingQuality=performance

; F7
; game/default/high/epic/insane/evenhigher; Hardware Lumen only - increases the raytracing radius to include more objects further away - particularly noticeable in reflections - recommend turning this up and screen space reflections off
RayTracingRadius=high

; default/less_50/less_25/more_25/more_50/more_75/more_100; changes intensity of the skylight - note that to see this setting change you will need to turn camera 360 - press the "+/=" key to apply it live
SkylightIntensity=more_25

; off/uplus_choice/uplus_choice_brighter/interiors_zero/custom; controls the skylight per location in the game according to the selected profile - goal is to tune the global light sources to be more correct and amplify the effect of local light sources, custom can be tuned to your own liking via copying skylight_uplus_choice.ini and creating skylight_custom.ini inside of the ue4ss UltraPlusExtensions config folder
SkylightLocationProfile=uplus_choice_v2

; game/default/high/epic/max_without_issues/insane/evenhigher; increases the distance that high quality volumetric fog is rendered, this can greatly improve the issue with vanilla fog being an overly white blob too close to the player
VolumetricFogDistance=game

; off/cozy/balanced/subtle; makes lights in cities brighter and more diffuse
TuneCityLights=balanced

; off/cozy/balanced/subtle; makes lights in interiors like inns and shops brighter and more diffuse
TuneInteriorLights=subtle

; off/on; reduces and changes behavior of outdoor volumetric fog to make it less invasive and less scattered
TuneOutdoorFog=on

; off/on; enables light transmission through materials like skin and adjust/improves the quality of skin - must restart game
SkinAndLightEnhancements=on

; CTRL + F6
; game/vanilla/morecontrast; 
PostProcessingTonemapperPreset=morecontrast

; game/none/percent_10/percent_20/percent_30/percent_40/percent_50/percent_60/percent_70/percent_80/percent_90/percent_100; amount that light shafts blur or spread across the screen, percent_100 is vanilla
LightShaftBlur=percent_50

; off/on; makes the torches not have a 2 foot radius and blind you - need to unequip and reequip torch if changing live
BetterTorches=on

; off/on/disable_emissive; controls volumetric fog
DisableFogIndoors=disable_emissive