; This configuration file loads on game startup
; In-game keybinds are disabled by default, set EnableKeybinds=on below to enable them on game start - or it can be turned on in game
; Press F12 to load the current configuration file while in-game - you can now edit the configuration file and load the changes while in-game
; If a setting does not specify a keybind, then it can only be changed via the configuration file
; The 'game' option for settings below tells Ultra Plus to leave the setting at game default
; CTRL+F12 will reset the configuration file to default values - you may need to restart game for "game" controlled settings to load game values

; CTRL + F3
; off/percent_20/percent_40/percent_60/percent_80/percent_100; changes intensity of bloom
Bloom=percent_100

; game/off/on;
ChromaticAberration=game

; off/on; fixes fog on DLSS4
DLSSAutoExposure=on

; F2
; game/none/temporal/rayreconstruction;
Denoiser=temporal

; game/off/on; allows turning off depth of field which can cause a lot of noise in cutscenes/dialogue - note that enabling RR already turns depth of field off
DepthOfField=game

; off/on/disable_emissive; controls volumetric fog
DisableFogIndoors=off

; off/on; off disables all keybinds except for F12 which loads the current configuration file in game - can be toggled on in-game by setting to on in config and pressing F12
EnableKeybinds=off

; game/ultra/insane; extends fog quality setting - increases the resolution of fog 
ExtendedFogQuality=game

; game/default/ultra/insane/more_insane/even_more_insane; extends view distances for lights, skeletal meshes, and static meshes
ExtendedViewDistance=game

; vanilla/more_stable; provides option to use more stable eye adaptation - may require tuning image to your liking - this was enabled by default in prior versions
EyeAdaptation=vanilla

; F4
; off/on; fixes the foliage and other outline artifacts against the sky but causes some above water flickering when player is underwater
FixFoliageAgainstSky=off

; F10
; game/off/on/on_with_lumen; allows disabling the color grading that applies a fantasy color map to the game, turn off if you want try a more realistic feel
Fog=on

; game/percent_50/percent_60/percent_70/percent_80/percent_90/percent_100/percent_150/percent_200/percent_250/percent_300/percent_350/percent_400/percent_450/percent_500; changes density of grass
GrassDensity=percent_80

; CTRL + F9
; lumen/ssao/gtao; ambient occlusion method - SSAO is vanilla, Lumen is U+ default
LightingAO=ssao

; F6
; lighting_mode_controlled/x48/x32/x24/x16/x8; allow users the ability to downsample the lighting more than the mod allows by default, it will be applied after other lighting settings - this is one of the settings that impacts performance the most - by default U+ runs at x24 in standard mode
LightingDownsampleFactorOverride=x16

; F8
; standard/advanced; standard for default enhanced lighting, advanced for experimental lighting
LightingMode=standard

; CTRL + F10
; game/performance/standard/high/epic/insane; low for more FPS if you are really struggling with FPS, standard for default settings, high for higher VRAM usage and slight performance hit, epic for higher VRAM usage and performance hit, insane is maximum gather quality at standard resolution, insane_highres is maximum gather quality at higher resolution, noframes is the maximum possible lighting quality and probably only feasible for photos
LightingQuality=performance

; F4
; game/off/low/medium/high/reallyhigh/alltheblur;
MotionBlur=game

; F7
; game/default/high/epic/insane/evenhigher; Hardware Lumen only - increases the raytracing radius to include more objects further away - particularly noticeable in reflections - recommend turning this up and screen space reflections off
RayTracingRadius=game

; F9
; game/off/low/medium/high; controls smoothness of reflective surfaces - some bias is preferred for visual quality
ReflectionBias=game

; CTRL + F2
; default/two/three; allows increasing the number of reflections bounces
ReflectionBounces=default

; game/none/percent_10/percent_20/percent_30/percent_40/percent_50/percent_60/percent_70/percent_80/percent_90/percent_100;
Sharpness=game

; off/on; enables light transmission through materials like skin and adjust/improves the quality of skin - must restart game
SkinAndLightEnhancements=off

; default/less_50/less_37_5/less_25/less_12_5/more_12_5/more_25/more_37_5/more_50/more_75/more_100; changes intensity of the skylight - note that to see this setting change you will need to turn camera 360
SkylightIntensity=default

; default/less_50/less_37_5/less_25/less_12_5/more_12_5/more_25/more_37_5/more_50/more_75/more_100; changes intensity of the skylight for the night button - this is automated
SkylightIntensityNight=default

; off/uplus_choice/uplus_choice_brighter/interiors_zero/custom; controls the skylight per location in the game according to the selected profile - goal is to tune the global light sources to be more correct and amplify the effect of local light sources, custom can be tuned to your own liking via copying skylight_uplus_choice.ini and creating skylight_custom.ini inside of the ue4ss UltraPlusExtensions config folder
SkylightLocationProfile=off

; F3
; game/off/on
Vignette=game

; CTRL + F7
; off/on; controls volumetric fog
VolumetricFog=on

; off/cozy/balanced/subtle; makes lights in cities brighter and more diffuse
TuneCityLights=off

; off/cozy/balanced/subtle; makes lights in interiors like inns and shops brighter and more diffuse
TuneInteriorLights=off

; off/on; reduces and changes behavior of outdoor volumetric fog to make it less invasive and less scattered
TuneOutdoorFog=off

; CTRL + F8
; game/vanilla/vanilla_adjustedshadows/obluevion/neutral/vibrant/morevibrant;
PostProcessingPreset=vanilla

; CTRL + F6
; game/vanilla/morecontrast; 
PostProcessingTonemapperPreset=vanilla

; game/none/percent_10/percent_20/percent_30/percent_40/percent_50/percent_60/percent_70/percent_80/percent_90/percent_100; amount that light shafts blur or spread across the screen, percent_100 is vanilla
LightShaftBlur=percent_100

; off/on; makes the torches not have a 2 foot radius and blind you - need to unequip and reequip torch if changing live
BetterTorches=off