[ShadowQuality@0]
r.Shadow.Virtual.MaxPhysicalPages=1024
r.Shadow.Virtual.ResolutionLodBiasDirectional=0.0
r.Shadow.Virtual.ResolutionLodBiasDirectionalMoving=0.0
r.Shadow.Virtual.ResolutionLodBiasLocal=1.0
r.Shadow.Virtual.ResolutionLodBiasLocalMoving=2.0
r.Shadow.Virtual.SMRT.RayCountDirectional=0
r.Shadow.Virtual.SMRT.SamplesPerRayDirectional=2
r.Shadow.Virtual.SMRT.RayCountLocal=0
r.Shadow.Virtual.SMRT.SamplesPerRayLocal=2
;r.Streaming.PoolSize=600

[ShadowQuality@1]
r.Shadow.Virtual.MaxPhysicalPages=1536
r.Shadow.Virtual.ResolutionLodBiasDirectional=0.0
r.Shadow.Virtual.ResolutionLodBiasDirectionalMoving=0.0
r.Shadow.Virtual.ResolutionLodBiasLocal=1.0
r.Shadow.Virtual.ResolutionLodBiasLocalMoving=2.0
r.Shadow.Virtual.SMRT.RayCountDirectional=4
r.Shadow.Virtual.SMRT.SamplesPerRayDirectional=2
r.Shadow.Virtual.SMRT.RayCountLocal=4
r.Shadow.Virtual.SMRT.SamplesPerRayLocal=2
;r.Streaming.PoolSize=800

[ShadowQuality@2]
r.Shadow.Virtual.MaxPhysicalPages=2048
r.Shadow.Virtual.ResolutionLodBiasDirectional=-0.5
r.Shadow.Virtual.ResolutionLodBiasDirectionalMoving=-0.5
r.Shadow.Virtual.ResolutionLodBiasLocal=0.0
r.Shadow.Virtual.ResolutionLodBiasLocalMoving=1.0
r.Shadow.Virtual.SMRT.RayCountDirectional=8
r.Shadow.Virtual.SMRT.SamplesPerRayDirectional=4
r.Shadow.Virtual.SMRT.RayCountLocal=8
r.Shadow.Virtual.SMRT.SamplesPerRayLocal=4
;r.Streaming.PoolSize=1000

[ShadowQuality@3]
r.Shadow.Virtual.MaxPhysicalPages=3072
r.Shadow.Virtual.ResolutionLodBiasDirectional=-1.0
r.Shadow.Virtual.ResolutionLodBiasDirectionalMoving=-1.0
r.Shadow.Virtual.ResolutionLodBiasLocal=0.0
r.Shadow.Virtual.ResolutionLodBiasLocalMoving=1.0
r.Shadow.Virtual.SMRT.RayCountDirectional=8
r.Shadow.Virtual.SMRT.SamplesPerRayDirectional=4
r.Shadow.Virtual.SMRT.RayCountLocal=8
r.Shadow.Virtual.SMRT.SamplesPerRayLocal=4
;r.Streaming.PoolSize=1400

[GlobalIlluminationQuality@0]
r.Lumen.TranslucencyVolume.TraceFromVolume=0
r.VolumetricFog.GridSizeZ=64
r.SkyAtmosphere.MultiScatteringLUT.HighQuality=0

[GlobalIlluminationQuality@1]
r.Lumen.TranslucencyVolume.TraceFromVolume=0
r.VolumetricFog.GridSizeZ=64
r.SkyAtmosphere.MultiScatteringLUT.HighQuality=0

[GlobalIlluminationQuality@2]
r.Lumen.TranslucencyVolume.TraceFromVolume=0
r.VolumetricFog.GridSizeZ=96
r.SkyAtmosphere.MultiScatteringLUT.HighQuality=1

[GlobalIlluminationQuality@3]
r.Lumen.TranslucencyVolume.TraceFromVolume=1
r.VolumetricFog.GridSizeZ=128
r.SkyAtmosphere.MultiScatteringLUT.HighQuality=1

[ViewDistanceQuality@0]
r.ViewDistanceScale=0.5

[ViewDistanceQuality@1]
r.ViewDistanceScale=0.8

[ViewDistanceQuality@2]
r.ViewDistanceScale=1.5

[ViewDistanceQuality@3]
r.ViewDistanceScale=2.0

[PostProcessQuality@0]
r.MotionBlurQuality=3

[PostProcessQuality@1]
r.MotionBlurQuality=3

[PostProcessQuality@2]
r.MotionBlurQuality=3

[PostProcessQuality@3]
r.MotionBlurQuality=4

[FoliageQuality@0]
r.Lumen.Reflections.MaxRoughnessToTraceForFoliage=0.2

[FoliageQuality@1]
r.Lumen.Reflections.MaxRoughnessToTraceForFoliage=0.2

[FoliageQuality@2]
r.Lumen.Reflections.MaxRoughnessToTraceForFoliage=0.2

[FoliageQuality@3]
r.Lumen.Reflections.MaxRoughnessToTraceForFoliage=0.36

[TextureQuality@0]
r.VT.PoolSizeScale=1.0
r.VT.PoolSizeScale.Group0=1.0
r.VT.PoolSizeScale.Group1=1.0
r.VT.PoolSizeScale.Group2=1.0
r.VT.MaxUploadsPerFrame=32
r.VT.MaxUploadsPerFrame.Streaming=48
r.Streaming.PoolSize=600
r.Streaming.LimitPoolSizeToVRAM=1
r.VT.MaxAnisotropy=4
r.MaxAnisotropy=8
r.Nanite.MaxPixelsPerEdge=1.5

[TextureQuality@1]
r.VT.PoolSizeScale=1.5
r.VT.PoolSizeScale.Group0=1.5
r.VT.PoolSizeScale.Group1=1.5
r.VT.PoolSizeScale.Group2=1.5
r.VT.MaxUploadsPerFrame=32
r.VT.MaxUploadsPerFrame.Streaming=64
r.Streaming.PoolSize=800
r.Streaming.LimitPoolSizeToVRAM=1
r.VT.MaxAnisotropy=4
r.MaxAnisotropy=8
r.Nanite.MaxPixelsPerEdge=1.45

[TextureQuality@2]
r.VT.PoolSizeScale=2.0
r.VT.PoolSizeScale.Group0=2.0
r.VT.PoolSizeScale.Group1=2.0
r.VT.PoolSizeScale.Group2=2.0
r.VT.MaxUploadsPerFrame=48
r.VT.MaxUploadsPerFrame.Streaming=80
r.Streaming.LimitPoolSizeToVRAM=1
r.VT.MaxAnisotropy=8
r.MaxAnisotropy=8
r.Nanite.MaxPixelsPerEdge=1.35

[TextureQuality@3]
r.VT.PoolSizeScale=2.5
r.VT.PoolSizeScale.Group0=2.5
r.VT.PoolSizeScale.Group1=2.5
r.VT.PoolSizeScale.Group2=2.5
r.VT.MaxUploadsPerFrame=64
r.VT.MaxUploadsPerFrame.Streaming=96
r.Streaming.LimitPoolSizeToVRAM=1
r.VT.MaxAnisotropy=8
r.MaxAnisotropy=16
r.Nanite.MaxPixelsPerEdge=1.15

[EffectsQuality@0]
r.SSS.SampleSet=1
r.SSS.Quality=0
r.SSS.HalfRes=1
r.SkyAtmosphere.AerialPerspectiveLUT.FastApplyOnOpaque=1
r.SkyAtmosphere.FastSkyLUT=1
r.LightShaftDownSampleFactor=2
r.LightShaftAllowTAA=1
r.SceneColorFormat=4

[EffectsQuality@1]
r.SSS.SampleSet=2
r.SSS.Quality=1
r.SSS.HalfRes=1
r.SkyAtmosphere.AerialPerspectiveLUT.FastApplyOnOpaque=1
r.SkyAtmosphere.FastSkyLUT=1
r.LightShaftDownSampleFactor=2
r.LightShaftAllowTAA=1
r.SceneColorFormat=4

[EffectsQuality@2]
r.SSS.SampleSet=2
r.SSS.Quality=1
r.SSS.HalfRes=0
r.SkyAtmosphere.AerialPerspectiveLUT.FastApplyOnOpaque=0
r.SkyAtmosphere.FastSkyLUT=0
r.LightShaftDownSampleFactor=1
r.LightShaftAllowTAA=0
r.SceneColorFormat=4

[EffectsQuality@3]
r.SSS.SampleSet=2
r.SSS.Quality=1
r.SSS.HalfRes=0
r.SkyAtmosphere.AerialPerspectiveLUT.FastApplyOnOpaque=0
r.SkyAtmosphere.FastSkyLUT=0
r.LightShaftDownSampleFactor=1
r.LightShaftAllowTAA=0
r.SceneColorFormat=4
